/**
 * Integration tests for the Media & Storage service layer.
 *
 * Uses the real PostgreSQL test DB (mirroring build-engine.test.ts) plus the
 * dependency-injected in-memory StorageClient so no S3 is required.
 *
 * Coverage:
 *  1. initiateUpload (staff) succeeds and creates an `uploaded` media row
 *  2. Unsolicited/unsupported MIME is rejected at init
 *  3. Upload window closed → ForbiddenError before any URL is issued
 *  4. completeUpload with a genuine object enqueues 3 processing jobs
 *  5. completeUpload detects a content/signature mismatch
 *  6. Content-hash duplicate hint returns a duplicate payload (no new row)
 *  7. Guest upload init derives scope from the vault (publicId only; no ids/keys)
 *  8. Guest complete by public id verifies the object and increments the count
 *  9. Worker: missing object → content_hash exhausts attempts → media failed
 * 10. retryProcessingJobs resets a failed job → completes → media processed
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { eq, and, inArray } from "drizzle-orm";
import { randomUUID } from "node:crypto";
import sharp from "sharp";

import { db } from "@/lib/db";
import {
  media,
  mediaProcessingJobs,
  memories,
  guestSessions,
  vaults,
  weddings,
  products,
  customers,
  organizations,
} from "@/lib/db/schema";
import { hashToken } from "@/lib/auth/token-utils";
import {
  MediaMimeRejectedError,
  MediaSignatureRejectedError,
  MediaSizeExceededError,
  GuestTokenInvalidError,
  ForbiddenError,
  NotFoundError,
} from "@/lib/auth/errors";
import {
  initiateUpload,
  initiateGuestUpload,
  completeUpload,
  completeGuestUploadByPublicId,
  retryProcessingJobs,
  listProcessingJobs,
  getMediaWithVariants,
  getSignedDownloadUrl,
  resolveEntitlementsForWedding,
  UPLOAD_URL_TTL_SECONDS,
} from "@/server/services/media-service";
import {
  executeMediaJob,
  maybeMarkMediaProcessed,
} from "@/server/services/media-worker";
import { memoryStorageClient, type StorageClient } from "@/server/services/storage/client";

// ── Test identities ────────────────────────────────────────────────────────────
// NOTE: deliberately distinct from build-engine.test.ts (which uses
// 00000000-... IDs) so the two DB-backed suites can run in parallel safely.

const TEST_ORG_ID = "11111111-1111-1111-1111-111111111101";
const TEST_CUSTOMER_ID = "11111111-1111-1111-1111-111111111102";
const TEST_WEDDING_ID = "11111111-1111-1111-1111-111111111103";
const TEST_PRODUCT_ID = "11111111-1111-1111-1111-111111111104";
const TEST_VAULT_ID = "11111111-1111-1111-1111-111111111105";

// Foreign tenant used to prove cross-tenant denial (IDOR guard).
const FOREIGN_ORG_ID = "22222222-2222-2222-2222-222222222201";
const FOREIGN_CUSTOMER_ID = "22222222-2222-2222-2222-222222222202";
const FOREIGN_WEDDING_ID = "22222222-2222-2222-2222-222222222203";
const FOREIGN_PRODUCT_ID = "22222222-2222-2222-2222-222222222204";
const FOREIGN_MEDIA_ID = "22222222-2222-2222-2222-222222222205";

// ── Fixtures ───────────────────────────────────────────────────────────────────

function futureWeddingDate(): Date {
  const d = new Date();
  d.setFullYear(d.getFullYear() + 1);
  d.setMonth(11); // December
  d.setDate(15);
  d.setHours(0, 0, 0, 0);
  return d;
}

function pastWeddingDate(): Date {
  const d = new Date();
  d.setFullYear(d.getFullYear() - 1);
  d.setMonth(1);
  d.setDate(15);
  d.setHours(0, 0, 0, 0);
  return d;
}

/** Minimal valid JPEG (generated by sharp at test time). */
async function makeJpeg(): Promise<Buffer> {
  return sharp({
    create: {
      width: 4,
      height: 4,
      channels: 3,
      background: { r: 220, g: 30, b: 40 },
    },
  })
    .jpeg({ quality: 80 })
    .toBuffer();
}

/** Minimal ISO-BMFF container accepted as video/mp4 (ftyp isom). */
function makeMinimalMp4(): Buffer {
  // Top-level ftyp box: size 24 + "ftyp" + major brand + minor + compatible brands.
  const buf = Buffer.alloc(24);
  buf.writeUInt32BE(24, 0);
  buf.write("ftyp", 4, "latin1");
  buf.write("isom", 8, "latin1");
  buf.writeUInt32BE(0, 12);
  buf.write("isom", 16, "latin1");
  buf.write("mp42", 20, "latin1");
  return buf;
}

async function setupTestData(packageCode: "silver" | "gold" | "platinum" = "gold") {
  await cleanupTestData();

  await db.insert(organizations).values({
    id: TEST_ORG_ID,
    publicId: "media-test-org-public-id",
    name: "Media Test Wedding Company",
    slug: "media-test-wedding-company",
    type: "wedding_company",
    status: "active",
  }).onConflictDoNothing();

  await db.insert(customers).values({
    id: TEST_CUSTOMER_ID,
    organizationId: TEST_ORG_ID,
    publicId: "media-test-customer-public-id",
    fullName: "Alice Smith",
    email: "media-test@example.com",
  }).onConflictDoNothing();

  // Org-scoped product (not platform-wide) so this suite never collides with
  // build-engine.test.ts on the platform-level unique product code.
  await db.insert(products).values({
    id: TEST_PRODUCT_ID,
    organizationId: TEST_ORG_ID,
    code: packageCode,
    name: packageCode.charAt(0).toUpperCase() + packageCode.slice(1),
    priceCents: packageCode === "silver" ? 59900 : packageCode === "gold" ? 79900 : 109900,
    status: "active",
  }).onConflictDoNothing();

  await db.insert(weddings).values({
    id: TEST_WEDDING_ID,
    organizationId: TEST_ORG_ID,
    customerId: TEST_CUSTOMER_ID,
    productId: TEST_PRODUCT_ID,
    publicId: "media-test-wedding-public-id",
    code: "WED-MEDIA-TEST-001",
    name: "Test Wedding",
    partnerOneName: "Alice",
    partnerTwoName: "Bob",
    weddingDate: futureWeddingDate(),
    status: "active",
  }).onConflictDoNothing();

  await db.insert(vaults).values({
    id: TEST_VAULT_ID,
    weddingId: TEST_WEDDING_ID,
    organizationId: TEST_ORG_ID,
    publicId: "media-test-vault-public-id",
    slug: "media-test-vault",
    title: "Test Vault",
    status: "published",
    publishedAt: new Date(),
  }).onConflictDoNothing();
}

async function cleanupTestData() {
  await db.delete(mediaProcessingJobs)
    .where(eq(mediaProcessingJobs.organizationId, TEST_ORG_ID));
  await db.delete(media).where(inArray(media.weddingId, [TEST_WEDDING_ID]));
  await db.delete(memories).where(eq(memories.weddingId, TEST_WEDDING_ID));
  await db.delete(guestSessions).where(eq(guestSessions.organizationId, TEST_ORG_ID));
  await db.delete(vaults).where(eq(vaults.weddingId, TEST_WEDDING_ID));
  await db.delete(weddings).where(eq(weddings.id, TEST_WEDDING_ID));
  await db.delete(products).where(eq(products.id, TEST_PRODUCT_ID));
  await db.delete(customers).where(eq(customers.id, TEST_CUSTOMER_ID));
  await db.delete(organizations).where(eq(organizations.id, TEST_ORG_ID));
}

/**
 * Seeds a fully separate foreign tenant (org, customer, product, wedding) so
 * cross-tenant media-access tests have a real second organization to assert
 * isolation against.
 */
async function setupForeignTenant(): Promise<void> {
  await db.insert(organizations).values({
    id: FOREIGN_ORG_ID,
    publicId: "media-test-foreign-org",
    name: "Foreign Wedding Company",
    slug: "media-test-foreign-company",
    type: "wedding_company",
    status: "active",
  }).onConflictDoNothing();

  await db.insert(customers).values({
    id: FOREIGN_CUSTOMER_ID,
    organizationId: FOREIGN_ORG_ID,
    publicId: "media-test-foreign-customer",
    fullName: "Carol Foreign",
    email: "foreign@example.com",
  }).onConflictDoNothing();

  await db.insert(products).values({
    id: FOREIGN_PRODUCT_ID,
    organizationId: FOREIGN_ORG_ID,
    code: "gold",
    name: "Gold",
    priceCents: 79900,
    status: "active",
  }).onConflictDoNothing();

  await db.insert(weddings).values({
    id: FOREIGN_WEDDING_ID,
    organizationId: FOREIGN_ORG_ID,
    customerId: FOREIGN_CUSTOMER_ID,
    productId: FOREIGN_PRODUCT_ID,
    publicId: "media-test-foreign-wedding",
    code: "WED-MEDIA-FOREIGN-001",
    name: "Foreign Wedding",
    weddingDate: futureWeddingDate(),
    status: "active",
  }).onConflictDoNothing();

  await db.insert(media).values({
    id: FOREIGN_MEDIA_ID,
    publicId: `${FOREIGN_MEDIA_ID.replace(/-/g, "").slice(0, 32)}`,
    weddingId: FOREIGN_WEDDING_ID,
    organizationId: FOREIGN_ORG_ID,
    storageKey: `${FOREIGN_ORG_ID}/${FOREIGN_WEDDING_ID}/${FOREIGN_MEDIA_ID}.jpg`,
    filename: "foreign.jpg",
    contentType: "image/jpeg",
    sizeBytes: 1_000,
    status: "processed",
  }).onConflictDoNothing();
}

async function cleanupForeignTenant() {
  await db.delete(media).where(eq(media.id, FOREIGN_MEDIA_ID));
  await db.delete(weddings).where(eq(weddings.id, FOREIGN_WEDDING_ID));
  await db.delete(products).where(eq(products.id, FOREIGN_PRODUCT_ID));
  await db.delete(customers).where(eq(customers.id, FOREIGN_CUSTOMER_ID));
  await db.delete(organizations).where(eq(organizations.id, FOREIGN_ORG_ID));
}

async function getMediaRow(mediaId: string) {
  const [row] = await db.select().from(media).where(eq(media.id, mediaId)).limit(1);
  return row;
}

async function getMediaRowByPublicId(publicId: string) {
  const [row] = await db.select().from(media).where(eq(media.publicId, publicId)).limit(1);
  return row;
}

/** Runs every pending job for a media item until none remain (worker simulation). */
async function drainJobs(mediaId: string, storage: StorageClient): Promise<void> {
  let guard = 0;
  for (;;) {
    guard += 1;
    if (guard > 30) throw new Error("drainJobs did not converge");

    const jobs = await db
      .select()
      .from(mediaProcessingJobs)
      .where(eq(mediaProcessingJobs.mediaId, mediaId));

    const pending = jobs.filter((j) => j.status === "pending");
    if (pending.length === 0) {
      await maybeMarkMediaProcessed(mediaId);
      return;
    }
    for (const job of pending) {
      await executeMediaJob(job.id, storage);
    }
  }
}

// ── Tests ──────────────────────────────────────────────────────────────────────

describe("Media & Storage service", () => {
  beforeEach(async () => {
    await setupTestData("gold");
  });

  afterEach(async () => {
    await cleanupTestData();
  });

  describe("initiateUpload", () => {
    it("1. succeeds for staff and creates an uploaded media row with a presigned URL", async () => {
      const storage = memoryStorageClient();
      const entitlements = await resolveEntitlementsForWedding(TEST_WEDDING_ID, TEST_ORG_ID);

      const result = await initiateUpload(
        { filename: "ring.jpg", contentType: "image/jpeg", sizeBytes: 5_000 },
        {
          organizationId: TEST_ORG_ID,
          weddingId: TEST_WEDDING_ID,
          entitlements,
          storage,
          origin: "staff",
        },
      );

      expect(result.mediaId).toBeDefined();
      expect(result.uploadUrl).toBeDefined();
      expect(result.storageKey).toMatch(new RegExp(`^${TEST_ORG_ID}/${TEST_WEDDING_ID}/`));
      expect(result.uploadUrl!.startsWith("memory://")).toBe(true);
      expect(result.expiresAt).toBeDefined();
      expect(Date.parse(result.expiresAt!) - Date.now()).toBeLessThanOrEqual(
        UPLOAD_URL_TTL_SECONDS * 1000,
      );
const row = await getMediaRow(result.mediaId!);
      expect(row).toBeDefined();
      expect(row!.organizationId).toBe(TEST_ORG_ID);
      expect(row!.weddingId).toBe(TEST_WEDDING_ID);
      expect(row!.status).toBe("uploaded");
      expect(row!.contentType).toBe("image/jpeg");
      expect(row!.filename).toBe("ring.jpg");
      expect(row!.storageKey.endsWith(".jpg")).toBe(true);
    });

    it("2. rejects unsupported MIME types before any URL is issued", async () => {
      const storage = memoryStorageClient();
      const entitlements = await resolveEntitlementsForWedding(TEST_WEDDING_ID, TEST_ORG_ID);

      await expect(
        initiateUpload(
          { filename: "payload.exe", contentType: "application/octet-stream", sizeBytes: 100 },
          {
            organizationId: TEST_ORG_ID,
            weddingId: TEST_WEDDING_ID,
            entitlements,
            storage,
            origin: "staff",
          },
        ),
      ).rejects.toBeInstanceOf(MediaMimeRejectedError);

      const rows = await db.select().from(media).where(eq(media.weddingId, TEST_WEDDING_ID));
      expect(rows).toHaveLength(0);
    });

    it("3. refuses uploads after the upload window closes", async () => {
      // Move the wedding into the past so the upload deadline has passed.
      await db
        .update(weddings)
        .set({ weddingDate: pastWeddingDate() })
        .where(eq(weddings.id, TEST_WEDDING_ID));

      const storage = memoryStorageClient();
      const entitlements = await resolveEntitlementsForWedding(TEST_WEDDING_ID, TEST_ORG_ID);
      expect(entitlements.uploadOpen).toBe(false);

      await expect(
        initiateUpload(
          { filename: "late.jpg", contentType: "image/jpeg", sizeBytes: 5_000 },
          {
            organizationId: TEST_ORG_ID,
            weddingId: TEST_WEDDING_ID,
            entitlements,
            storage,
            origin: "staff",
          },
        ),
      ).rejects.toBeInstanceOf(ForbiddenError);
    });

    it("3b. rejects files above the package size limit (photo > 25 MB)", async () => {
      const storage = memoryStorageClient();
      const entitlements = await resolveEntitlementsForWedding(TEST_WEDDING_ID, TEST_ORG_ID);

      await expect(
        initiateUpload(
          { filename: "huge.jpg", contentType: "image/jpeg", sizeBytes: 26 * 1024 * 1024 },
          {
            organizationId: TEST_ORG_ID,
            weddingId: TEST_WEDDING_ID,
            entitlements,
            storage,
            origin: "staff",
          },
        ),
      ).rejects.toBeInstanceOf(MediaSizeExceededError);

      const rows = await db.select().from(media).where(eq(media.weddingId, TEST_WEDDING_ID));
      expect(rows).toHaveLength(0);
    });

    it("3c. rejects videos above the package limit (video > 250 MB) even when entitled", async () => {
      const storage = memoryStorageClient();
      const entitlements = await resolveEntitlementsForWedding(TEST_WEDDING_ID, TEST_ORG_ID);
      // Gold is entitled to video in these fixtures.
      expect(entitlements.features.video).toBe(true);

      await expect(
        initiateUpload(
          { filename: "huge.mp4", contentType: "video/mp4", sizeBytes: 251 * 1024 * 1024 },
          {
            organizationId: TEST_ORG_ID,
            weddingId: TEST_WEDDING_ID,
            entitlements,
            storage,
            origin: "staff",
          },
        ),
      ).rejects.toBeInstanceOf(MediaSizeExceededError);
    });
  });

  describe("completeUpload", () => {
    it("4. verifies the stored object and enqueues 3 processing jobs for an image", async () => {
      const storage = memoryStorageClient();
      const entitlements = await resolveEntitlementsForWedding(TEST_WEDDING_ID, TEST_ORG_ID);

      const { mediaId, storageKey } = await initiateUpload(
        { filename: "photo.jpg", contentType: "image/jpeg", sizeBytes: 4_000 },
        {
          organizationId: TEST_ORG_ID,
          weddingId: TEST_WEDDING_ID,
          entitlements,
          storage,
          origin: "staff",
        },
      );
      if (!mediaId) throw new Error("expected mediaId from initiateUpload");
      await storage.putObject(storageKey!, await makeJpeg(), { contentType: "image/jpeg" });

      const result = await completeUpload(mediaId, TEST_ORG_ID, { storage });
      expect(result.status).toBe("processing");

      const row = await getMediaRow(mediaId);
      expect(row!.status).toBe("processing");
      // Real stored size re-checked against the object.
      expect(row!.sizeBytes).toBeGreaterThan(0);

      const jobs = await listProcessingJobs(mediaId, TEST_ORG_ID);
      expect(jobs.map((j) => j.jobType).sort()).toEqual(
        ["content_hash", "optimize", "thumbnail"].sort(),
      );
      expect(jobs.every((j) => j.status === "pending")).toBe(true);
      expect(jobs.every((j) => j.idempotencyKey.startsWith(`media:${mediaId}:`))).toBe(true);
      expect(jobs.every((j) => j.maxAttempts === 3)).toBe(true);
    });

    it("5. rejects uploaded content whose magic bytes do not match the declaration", async () => {
      const storage = memoryStorageClient();
      const entitlements = await resolveEntitlementsForWedding(TEST_WEDDING_ID, TEST_ORG_ID);

      const { mediaId, storageKey } = await initiateUpload(
        { filename: "html-disguised.jpg", contentType: "image/jpeg", sizeBytes: 200 },
        {
          organizationId: TEST_ORG_ID,
          weddingId: TEST_WEDDING_ID,
          entitlements,
          storage,
          origin: "staff",
        },
      );
      if (!mediaId) throw new Error("expected mediaId from initiateUpload");
      await storage.putObject(storageKey!, Buffer.from("<html><script>alert(1)</script></html>"));

      await expect(completeUpload(mediaId, TEST_ORG_ID, { storage })).rejects.toBeInstanceOf(
        MediaSignatureRejectedError,
      );
    });
  });

  describe("duplicate detection", () => {
    it("6. returns a duplicate payload when the sha256 hint matches an existing media item", async () => {
      const storage = memoryStorageClient();
      const entitlements = await resolveEntitlementsForWedding(TEST_WEDDING_ID, TEST_ORG_ID);
      const hash = "a".repeat(64);

      const first = await initiateUpload(
        { filename: "a.jpg", contentType: "image/jpeg", sizeBytes: 1_000, sha256: hash },
        {
          organizationId: TEST_ORG_ID,
          weddingId: TEST_WEDDING_ID,
          entitlements,
          storage,
          origin: "staff",
        },
      );

      const second = await initiateUpload(
        { filename: "b.jpg", contentType: "image/jpeg", sizeBytes: 1_000, sha256: hash },
        {
          organizationId: TEST_ORG_ID,
          weddingId: TEST_WEDDING_ID,
          entitlements,
          storage,
          origin: "staff",
        },
      );

      expect(second.duplicate).toBe(true);
      expect(second.duplicateOf).toBe(first.mediaId);
      expect(second.storageKey).toBeUndefined();

      // No new media row was created for the duplicate.
      const rows = await db.select().from(media).where(eq(media.weddingId, TEST_WEDDING_ID));
      expect(rows).toHaveLength(1);
    });
  });

  describe("guest uploads", () => {
    async function createGuestSession(maxUploads = 100): Promise<{ rawToken: string; id: string }> {
      const rawToken = randomUUID().replace(/-/g, "");
      const [session] = await db
        .insert(guestSessions)
        .values({
          vaultId: TEST_VAULT_ID,
          organizationId: TEST_ORG_ID,
          token: hashToken(rawToken),
          displayName: "Guest One",
          status: "active",
          expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
          maxUploads,
        })
        .returning({ id: guestSessions.id });
      return { rawToken, id: session.id };
    }

    it("7. derives scope from the guest's vault and never exposes internal ids or storage keys", async () => {
      const { rawToken, id: sessionId } = await createGuestSession();

      const result = await initiateGuestUpload(rawToken, {
        filename: "guest-photo.jpg",
        contentType: "image/jpeg",
        sizeBytes: 2_500,
      });

      // Guest contract: opaque publicId, no internal mediaId, no storage key.
      expect(result.mediaId).toBeUndefined();
      expect(result.publicId).toBeDefined();
      expect(result.publicId).toMatch(/^[a-f0-9]{32}$/);
      expect(result.uploadUrl).toBeDefined();
      expect(result.uploadUrl!.startsWith("memory://")).toBe(true);
      expect(result.storageKey).toBeUndefined();
      expect(result.duplicateOf).toBeUndefined();

      const row = await getMediaRowByPublicId(result.publicId!);
      expect(row!.organizationId).toBe(TEST_ORG_ID);
      expect(row!.weddingId).toBe(TEST_WEDDING_ID);
      expect(row!.guestSessionId).toBe(sessionId);
      expect(row!.uploadedBy).toBeNull();
    });

    it("7b. rejects an unauthorized upload attempt (invalid/absent guest token) and creates no rows", async () => {
      await expect(
        initiateGuestUpload("no-such-token-0123456789abcdef", {
          filename: "x.jpg",
          contentType: "image/jpeg",
          sizeBytes: 100,
        }),
      ).rejects.toBeInstanceOf(GuestTokenInvalidError);

      const rows = await db
        .select({ id: media.id })
        .from(media)
        .where(eq(media.weddingId, TEST_WEDDING_ID));
      expect(rows).toHaveLength(0);
    });

    it("8. completes a guest upload by public id and increments the session count", async () => {
      const storage = memoryStorageClient();
      const { rawToken } = await createGuestSession();

      const result = await initiateGuestUpload(rawToken, {
        filename: "guest-photo.jpg",
        contentType: "image/jpeg",
        sizeBytes: 2_500,
      });

      const row = await getMediaRowByPublicId(result.publicId!);
      await storage.putObject(row!.storageKey, await makeJpeg(), { contentType: "image/jpeg" });

      // Completion is addressed by opaque public id, scoped to the session.
      const completed = await completeGuestUploadByPublicId(rawToken, result.publicId!, { storage });
      expect(completed.status).toBe("processing");
      expect(completed.publicId).toBe(result.publicId);

      const [session] = await db
        .select()
        .from(guestSessions)
        .where(eq(guestSessions.id, row!.guestSessionId!))
        .limit(1);
      expect(session!.uploadCount).toBe(1);

      // Guest uploads go through the same processing pipeline.
      const jobs = await listProcessingJobs(row!.id, TEST_ORG_ID);
      expect(jobs).toHaveLength(3);
    });
  });

  describe("processing worker & retries", () => {
    it("9. fails a job permanently after exhausting attempts when the object is missing", async () => {
      const storage = memoryStorageClient();
      const entitlements = await resolveEntitlementsForWedding(TEST_WEDDING_ID, TEST_ORG_ID);

      const { mediaId, storageKey } = await initiateUpload(
        { filename: "photo.jpg", contentType: "image/jpeg", sizeBytes: 4_000 },
        {
          organizationId: TEST_ORG_ID,
          weddingId: TEST_WEDDING_ID,
          entitlements,
          storage,
          origin: "staff",
        },
      );
      if (!mediaId) throw new Error("expected mediaId from initiateUpload");
      await storage.putObject(storageKey!, await makeJpeg(), { contentType: "image/jpeg" });
      await completeUpload(mediaId, TEST_ORG_ID, { storage });

      // Simulate a storage failure after completion: the object vanishes.
      await storage.deleteObject(storageKey!);

      await drainJobs(mediaId, storage);

      const [contentHashJob] = await db
        .select()
        .from(mediaProcessingJobs)
        .where(and(eq(mediaProcessingJobs.mediaId, mediaId), eq(mediaProcessingJobs.jobType, "content_hash")))
        .limit(1);

      expect(contentHashJob!.status).toBe("failed");
      expect(contentHashJob!.attempts).toBe(3);
      expect(contentHashJob!.errorMessage).toBeTruthy();

      const row = await getMediaRow(mediaId);
      expect(row!.status).toBe("failed");
    });

    it("10. retries a permanently failed job and converges the media to processed", async () => {
      const storage = memoryStorageClient();
      const entitlements = await resolveEntitlementsForWedding(TEST_WEDDING_ID, TEST_ORG_ID);

      const { mediaId, storageKey } = await initiateUpload(
        { filename: "clip.mov", contentType: "video/quicktime", sizeBytes: 60_000 },
        {
          organizationId: TEST_ORG_ID,
          weddingId: TEST_WEDDING_ID,
          entitlements,
          storage,
          origin: "staff",
        },
      );
      if (!mediaId) throw new Error("expected mediaId from initiateUpload");
      await storage.putObject(storageKey!, makeMinimalMp4(), { contentType: "video/quicktime" });
      await completeUpload(mediaId, TEST_ORG_ID, { storage });

      // Manually fail the content_hash job to simulate a permanent failure.
      const [contentHashJob] = await db
        .select({ id: mediaProcessingJobs.id })
        .from(mediaProcessingJobs)
        .where(and(eq(mediaProcessingJobs.mediaId, mediaId), eq(mediaProcessingJobs.jobType, "content_hash")))
        .limit(1);
      await db
        .update(mediaProcessingJobs)
        .set({ status: "failed", errorMessage: "simulated permanent failure", attempts: 3 })
        .where(eq(mediaProcessingJobs.id, contentHashJob!.id));

      const retry = await retryProcessingJobs(mediaId, TEST_ORG_ID);
      expect(retry.reset).toBe(1);

      const [resetJob] = await db
        .select()
        .from(mediaProcessingJobs)
        .where(eq(mediaProcessingJobs.id, contentHashJob!.id))
        .limit(1);
      expect(resetJob!.status).toBe("pending");
      expect(resetJob!.attempts).toBe(0);
      expect(resetJob!.errorMessage).toBeNull();

      await drainJobs(mediaId, storage);

      const [completedJob] = await db
        .select({ status: mediaProcessingJobs.status })
        .from(mediaProcessingJobs)
        .where(eq(mediaProcessingJobs.id, contentHashJob!.id))
        .limit(1);
      expect(completedJob!.status).toBe("completed");

      const row = await getMediaRow(mediaId);
      expect(row!.status).toBe("processed");
    });
  });

  describe("tenant isolation & expiry enforcement", () => {
    it("11. denies cross-tenant media access (foreign media is invisible)", async () => {
      await setupForeignTenant();

      try {
        // A caller scoped to the TEST org must not see media owned by the
        // foreign org — NotFound, never a leak of foreign data.
        await expect(getMediaWithVariants(FOREIGN_MEDIA_ID, TEST_ORG_ID)).rejects.toBeInstanceOf(
          NotFoundError,
        );

        const foreignEntitlements = await resolveEntitlementsForWedding(
          FOREIGN_WEDDING_ID,
          FOREIGN_ORG_ID,
        );
        await expect(
          getSignedDownloadUrl(FOREIGN_MEDIA_ID, TEST_ORG_ID, {
            entitlements: foreignEntitlements,
          }),
        ).rejects.toBeInstanceOf(NotFoundError);
      } finally {
        await cleanupForeignTenant();
      }
    });

    it("12. refuses signed download URLs once the download window closes", async () => {
      const storage = memoryStorageClient();

      // Seed a processed media item (as if the upload pipeline had completed).
      const seedId = randomUUID();
      const seedKey = `${TEST_ORG_ID}/${TEST_WEDDING_ID}/${seedId}.jpg`;
      await db.insert(media).values({
        id: seedId,
        publicId: seedId.replace(/-/g, "").slice(0, 32),
        weddingId: TEST_WEDDING_ID,
        organizationId: TEST_ORG_ID,
        storageKey: seedKey,
        filename: "finished.jpg",
        contentType: "image/jpeg",
        sizeBytes: 1_000,
        status: "processed",
      });

      // Move the wedding into the past: downloads must now be denied.
      await db
        .update(weddings)
        .set({ weddingDate: pastWeddingDate() })
        .where(eq(weddings.id, TEST_WEDDING_ID));

      const closedEntitlements = await resolveEntitlementsForWedding(TEST_WEDDING_ID, TEST_ORG_ID);
      expect(closedEntitlements.downloadOpen).toBe(false);

      await expect(
        getSignedDownloadUrl(seedId, TEST_ORG_ID, {
          entitlements: closedEntitlements,
          storage,
        }),
      ).rejects.toBeInstanceOf(ForbiddenError);
    });
  });
});